alias: Mark a person as extended away
id: 5881c7a72a8e49bb98623f722f4d8f87
trigger:
- platform: state
  entity_id: input_select.thomas_status_dropdown
  to: unterwegs
  for:
    hours: 24
- platform: state
  entity_id: input_select.steffi_status_dropdown
  to: unterwegs
  for:
    hours: 24
action:
- service: input_select.select_option
  data_template:
    entity_id: "{% if trigger.entity_id == 'input_select.thomas_status_dropdown'\
      \ %}\n  input_select.thomas_status_dropdown\n{% else %}\n  input_select.steffi_status_dropdown\n\
      {% endif %}\n"
    option: lange weg
