- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "home/thomaszimmer/sonoff/cmnd/POWER"
        payload: ""
