- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "home/thomaszimmer/sonoff/cmnd/POWER"
        payload: ""
- alias: "Müllabfuhr-Benachrichtung"
  trigger:
    platform: state
    entity_id: calendar.jarvis_muellabfuhr
    to: "on"
  action:
    - service: notify.jarvisnotifier
      data:
        title: "Müllabfuhr-Benachrichtigung"
        message: "Morgen wird {{ states.calendar.jarvis_muellabfuhr.attributes.description }} abgeholt!"
