- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "home/thomaszimmer/sonoff/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "home/keller/waschmaschine/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "home/keller/sonoff/cmnd/POWER"
        payload: ""
- alias: "Müllabfuhr-Benachrichtung"
  trigger:
    platform: state
    entity_id: calendar.jarvis_muellabfuhr
    to: "on"
  action:
    - service: notify.jarvisnotifier
      data:
        title: "Müllabfuhr-Benachrichtigung"
        message: "Morgen wird {{ states.calendar.jarvis_muellabfuhr.attributes.description }} abgeholt!"
- alias: "Stromausfall"
  trigger:
    platform: state
    entity_id: sensor.ups_status
    to: "ONBATT"
    for:
      seconds: 30
  action:
    - service: notify.jarvisnotifier
      data:
        title: "Stromausfall erkannt"
        message: "Die Batterie hält ca. {{ states.sensor.ups_time_left.state | int() }} Minuten!"
- alias: "Wäsche ist fertig"
  trigger:
    platform: state
    entity_id: binary_sensor.waschmaschine
    to: "off"
    for:
      minutes: 2
  action:
    - service: notify.jarvisnotifier
      data:
        title: "Wäsche ist fertig"
        message: "Die Waschmaschine ist seit 5 Minuten aus."
- alias: "Rechner einschalten"
  trigger:
    platform: mqtt
    topic: home/thomaszimmer/temperatur/button
    payload: 'clicked'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.sonoff_rechner
- alias: "Rechner ausschalten"
  trigger:
    platform: mqtt
    topic: home/thomaszimmer/temperatur/button
    payload: 'held'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.sonoff_rechner
- alias: "Thomas geht schlafen"
  trigger:
    platform: mqtt
    topic: home/thomaszimmer/temperatur/button
    payload: 'heldLong'
  action:
    service: switch.turn_off
    data:
      entity_id: group.thomaszimmer
- alias: "Wöchentliches Backup"
  trigger:
    platform: time
    at: "01:00:00"
  condition:
    condition: time
    weekday:
      - mon
  action:
    - service: hassio.snapshot_full
      data_template:
        name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
- alias: "Backup hochladen"
  trigger:
    platform: time
    at: "02:00:00"
  condition:
    condition: time
    weekday:
      - mon
  action:
    - service: hassio.addon_stdin
      data:
        addon: 7be23ff5_dropbox_sync
        input: {"command":"upload"}
