- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "home/thomaszimmer/sonoff/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "home/keller/waschmaschine/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "home/keller/sonoff/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'shellies/command'
        payload: 'update'
- alias: "Wöchentliches Backup"
  trigger:
    platform: time
    at: "01:00:00"
  condition:
    condition: time
    weekday:
      - mon
  action:
    - service: hassio.snapshot_full
      data_template:
        name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
        password: !secret http_password

# - alias: NeoPixel Animation Speed Send
#   initial_state: true
#   hide_entity: false
#   trigger:
#   - entity_id: input_number.neopixel_animation_speed
#     platform: state
#   action:
#   - data_template:
#       payload_template: '{"speed": {{ trigger.to_state.state | int }}}'
#       retain: true
#       topic: home/McLightingThomas_ha/state/in
#     service: mqtt.publish

# - alias: NeoPixel Animation Speed Receive
#   trigger:
#   - platform: mqtt
#     topic: home/McLightingThomas_ha/state/out
#   action:
#   - data_template:
#       entity_id: input_number.neopixel_animation_speed
#       value: '{{ trigger.payload_json.speed | int }}'
#     service: input_number.set_value
