- id: '1569956400494'
  alias: Alexa Timer
  trigger:
  - platform: template
    value_template: '{% if not is_state("sensor.thomas_next_timer", "None") -%}

      {{as_timestamp(now()) > as_timestamp(states("sensor.thomas_next_timer"))}}

      {%- else -%}

      False

      {%- endif -%}'
  condition: []
  action:
  - data:
      message: Timer abgelaufen
    service: system_log.write
- id: '1570806214584'
  alias: Set Theme on Startup
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: slate
    service: frontend.set_theme
