homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 53.086612
  longitude: 8.792995
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 11
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Floorplan
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# TasmoAdmin
panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: http://192.168.2.130:9541

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  base_url: helmkeaufdemkamp.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# InfluxDB
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret mqtt_user
  password: !secret mqtt_pass
  max_retries: 3
  default_measurement: state

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# USV
apcupsd:
  host: a722577e-apcupsd

# Weather prediction
sensor:
  - platform: yr
    name: Wetter Heute
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
  - platform: yr
    name: Wetter Morgen
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
  - platform: mqtt
    name: "Wohnzimmer Temperatur"
    unit_of_measurement: "°C"
    state_topic: "home/wohnzimmer/temperatur"
    value_template: '{{ value_json.temp }}'
  - platform: mqtt
    name: "Wohnzimmer Luftdruck"
    unit_of_measurement: "hPa"
    icon: mdi:gauge
    state_topic: "home/wohnzimmer/temperatur"
    value_template: '{{ value_json.press }}'
  - platform: mqtt
    name: "Wohnzimmer Luftfeuchtigkeit"
    unit_of_measurement: "%"
    icon: mdi:water-percent
    state_topic: "home/wohnzimmer/temperatur"
    value_template: '{{ value_json.humid }}'
  - platform: mqtt
    name: "Steffis Zimmer Temperatur"
    unit_of_measurement: "°C"
    state_topic: "home/steffiszimmer/temperatur"
    value_template: '{{ value_json.temp }}'
  - platform: mqtt
    name: "Steffis Zimmer Luftdruck"
    unit_of_measurement: "hPa"
    icon: mdi:gauge
    state_topic: "home/steffiszimmer/temperatur"
    value_template: '{{ value_json.press }}'
  - platform: mqtt
    name: "Steffis Zimmer Luftfeuchtigkeit"
    unit_of_measurement: "%"
    icon: mdi:water-percent
    state_topic: "home/steffiszimmer/temperatur"
    value_template: '{{ value_json.humid }}'
  - platform: mqtt
    name: "Thomas' Zimmer Temperatur"
    unit_of_measurement: "°C"
    state_topic: "home/thomaszimmer/temperatur"
    value_template: '{{ value_json.temp }}'
  - platform: mqtt
    name: "Thomas' Zimmer Luftdruck"
    unit_of_measurement: "hPa"
    icon: mdi:gauge
    state_topic: "home/thomaszimmer/temperatur"
    value_template: '{{ value_json.press }}'
  - platform: mqtt
    name: "Thomas' Zimmer Luftfeuchtigkeit"
    unit_of_measurement: "%"
    icon: mdi:water-percent
    state_topic: "home/thomaszimmer/temperatur"
    value_template: '{{ value_json.humid }}'
  - platform: apcupsd
    resources:
      - bcharge
      - linev
      - loadpct
      - nominv
      - nompower
      - numxfers
      - outputv
      - status
      - timeleft
      - tonbatt

switch:
  - platform: mqtt
    name: "Sonoff Rechner"
    state_topic: "home/thomaszimmer/sonoff/stat/RESULT" #"stat/sonoff/POWER"
    value_template: '{{ value_json["POWER"] }}'
    command_topic: "home/thomaszimmer/sonoff/cmnd/POWER" #"cmnd/sonoff/POWER"
    availability_topic: "home/thomaszimmer/sonoff/tele/LWT" #"tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Sonoff Keller"
    state_topic: "home/keller/sonoff/stat/RESULT" #"stat/sonoff/POWER"
    value_template: '{{ value_json["POWER"] }}'
    command_topic: "home/keller/sonoff/cmnd/POWER" #"cmnd/sonoff/POWER"
    availability_topic: "home/keller/sonoff/tele/LWT" #"tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: wake_on_lan
    mac_address: "00-11-32-37-21-3D"
    name: "Synology NAS"
    host: "192.168.2.151"
    turn_off:
      service: shell_command.turn_off_nas
      data:
        secret_url: !secret syno_cmd_url

shell_command:
  turn_off_nas: 'curl {{ secret_url }}'

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Google
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

# mqtt
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user
  password: !secret mqtt_pass

duckdns:
  domain: helmkeaufdemkamp
  access_token: !secret ducktoken

device_tracker:
  - platform: owntracks

telegram_bot:
  - platform: polling
    api_key: !secret telegram_apikey
    allowed_chat_ids:
      - !secret telegramm_group_id

notify:
  - name: JarvisNotifier
    platform: telegram
    chat_id: !secret telegramm_group_id

hdmi_cec:
  devices:
    TV: 0.0.0.0
    BlueRay Player: 1.0.0.0
    Raspberry: 4.0.0.0

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
