homeassistant:
  customize: !include customize.yaml

  whitelist_external_dirs:
    - /config/sensor
    - /share/sensor

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

hacs:
  token: !secret hacs_github
  
mobile_app:

# Enables configuration UI
config:

system_health:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  base_url: helmkeaufdemkamp.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# reduce DB size by configuring the recorder component
recorder:
#  purge_keep_days: 1
#  purge_interval: 1
  db_url: !secret maria_url
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.date

logger:
  default: info
  logs:
    pydeconz: debug
    homeassistant.components.deconz: debug
    abfallio: debug

# # InfluxDB
#influxdb:
#  host: a0d7b954-influxdb
#  port: 8086
#  database: homeassistant
#  username: homeassistant
#  password: !secret http_password
#  max_retries: 3
#  default_measurement: state

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set

weather:
  - platform: openweathermap
    api_key: !secret openweatherkey

# USV
apcupsd:
  host: a722577e-apcupsd

homematic:
  interfaces:
    rf:
      host: 192.168.2.120
      port: 2001
      resolvenames: json
      username: !secret homematic_user
      password: !secret homematic_pass
    ip:
      host: 192.168.2.120
      port: 2010
      resolvenames: json
      username: !secret homematic_user
      password: !secret homematic_pass
  hosts:
    ccu2:
      host: 192.168.2.120
      username: !secret homematic_user
      password: !secret homematic_pass

#android_ip_webcam:
#  - host: 192.168.2.127
#    sensors:
#      - battery_level
#      - battery_temp
#      - light
#    switches:
#      - night_vision
#      - torch

sensor:
  - platform: cups
    host: 192.168.2.101
    is_cups_server: false
    printers:
      - ipp/print
  - platform: apcupsd
    resources:
      - bcharge
      - linev
      - loadpct
      - nominv
      - nompower
      - numxfers
      # - outputv
      - status
      - timeleft
      - tonbatt
  - platform: mqtt
    name: "Waschmaschine Energie"
    state_topic: "home/keller/waschmaschine/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
    icon: mdi:gauge
  - platform: mqtt
    name: "Waschmaschine Leistung"
    state_topic: "home/keller/waschmaschine/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
    icon: mdi:gauge-full
  - platform: filter
    name: "Waschmaschine Leistung average"
    entity_id: sensor.waschmaschine_leistung
    filters:
      - filter: time_simple_moving_average
        window_size: 00:03
        precision: 2
  - platform: filter
    name: "Waschmaschine Leistung glatt"
    entity_id: sensor.waschmaschine_leistung
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 2
  - platform: mqtt
    name: "Waschmaschine Spannung"
    state_topic: "home/keller/waschmaschine/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
    icon: mdi:gauge-low
  - platform: mqtt
    name: "Waschmaschine Strom"
    state_topic: "home/keller/waschmaschine/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"
    icon: mdi:gauge-empty
  - platform: mqtt
    name: "Rollladen Thomas Temperatur"
    state_topic: "shellies/shellyswitch25-E62E12/temperature"
    unit_of_measurement: "°C"
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
  - platform: fritzbox_netmonitor
  - platform: template
    sensors:
      battery_thermo_bad:
        friendly_name: 'Thermostat Badezimmer'
        entity_id: climate.000393c99b850c
        value_template: "{{ states.climate['000393c99b850c'].attributes.battery if states.climate['000393c99b850c'] is not none }}"
        icon_template: "{% if is_state_attr('climate.000393c99b850c', 'battery', 'High') %}
                           mdi:battery
                        {% else %}
                           battery-outline
                        {% endif %}"
      battery_thermo_thomas:
        friendly_name: 'Thermostat Thomas'
        entity_id: climate.0012999395e750
        value_template: "{{ states.climate['0012999395e750'].attributes.battery if states.climate['0012999395e750'] is not none }}"
        icon_template: "{% if is_state_attr('climate.0012999395e750', 'battery', 'High') %}
                           mdi:battery
                        {% else %}
                           battery-outline
                        {% endif %}"
      battery_fenster_steffi:
        friendly_name: 'Fenster Steffi'
        entity_id: binary_sensor.fenster_steffi
        value_template: "{{ states.binary_sensor['fenster_steffi'].attributes.battery if states.binary_sensor['fenster_steffi'] is not none }}"
        icon_template: "{% if is_state_attr('binary_sensor.fenster_steffi', 'battery', 'High') %}
                           mdi:battery
                        {% else %}
                           battery-outline
                        {% endif %}"
      battery_keller_wasser:
        friendly_name: 'Keller Wasser'
        entity_id: binary_sensor.001898a99f52dc_alarmstate
        value_template: "{{ states.binary_sensor['001898a99f52dc_alarmstate'].attributes.battery if states.binary_sensor['001898a99f52dc_alarmstate'] is not none }}"
        icon_template: "{% if is_state_attr('binary_sensor.001898a99f52dc_alarmstate', 'battery', 'High') %}
                           mdi:battery
                        {% else %}
                           battery-outline
                        {% endif %}"
      fritz_uptime:
        friendly_name: "Fritzbox Uptime"
        icon_template: mdi:clock-outline
        value_template: "{% set uptime = states.sensor.fritz_netmonitor.attributes.uptime | int %}
                          {% set minutes = ((uptime % 3600) / 60) | int %} 
                          {% set hours = ((uptime % 86400) / 3600) | int %}
                          {% set days = (uptime / 86400) | int %}
                          {%- if uptime < 1 -%}
                            Weniger als eine Minute
                          {%- else -%}
                            {%- if days > 0 -%}
                              {%- if days == 1 -%}
                                1 Tag
                              {%- else -%}
                                {{ days }} Tage
                              {%- endif -%}
                            {%- endif -%}
                            {%- if hours > 0 -%}
                              {%- if days > 0 -%}
                                {{ ', ' }}
                              {%- endif -%}
                              {%- if hours == 1 -%}
                                1 Stunde
                              {%- else -%}
                                {{ hours }} Stunden
                              {%- endif -%}
                            {%- endif -%}
                            {%- if minutes > 0 -%}
                              {%- if days > 0 or hours > 0 -%}
                                {{ ', ' }}
                              {%- endif -%}
                              {%- if minutes == 1 -%}
                                1 Minute
                              {%- else -%}
                                {{ minutes }} Minuten
                              {%- endif -%}
                            {%- endif -%}
                          {%- endif -%}"
      fritz_download_rate:
        friendly_name: "Fritzbox Downstream"
        icon_template: mdi:download-network-outline
        unit_of_measurement: 'Mbit/s'
        value_template: "{{ states.sensor.fritz_netmonitor.attributes.transmission_rate_down/125000 }}"
      fritz_upload_rate:
        friendly_name: "Fritzbox Upstream"
        icon_template: mdi:upload-network-outline
        unit_of_measurement: 'bytes/s'
        value_template: "{{ states.sensor.fritz_netmonitor.attributes.transmission_rate_up }}"
      v_last_reboot:
        value_template: "{{ state_attr('homematic.ccu2', 'V_Last_Reboot') or '01.01.1970 00:00:00' }}"
        icon_template: "mdi:clock"
        entity_id: homematic.ccu2
      thomas_status:
        value_template: "{{ states.input_select.thomas_status_dropdown.state }}"
        friendly_name: Thomas
      steffi_status:
        value_template: "{{ states.input_select.steffi_status_dropdown.state }}"
        friendly_name: Steffi
      vicare_aussentemperatur:
        value_template: "{{state_attr('climate.vicare_heating', 'outside_temperature')}}"
        unit_of_measurement: "°C"
        friendly_name: Aussentemperatur
      raspberrymatic_new_firmware:
        friendly_name: RaspberryMatic
        value_template: >-
          {% if is_state_attr('homematic.ccu2','CCU Firmware Status', true) %}
            Neue Firmware vorhanden
          {% else %}
            Version aktuell
          {% endif %}
        icon_template: >-
          {% if is_state_attr('homematic.ccu2','CCU Firmware Status', true) %}
            mdi:briefcase-upload
          {% else %}
            mdi:briefcase-check
          {% endif %}
  - platform: file
    name: MuellabfuhrAbgeholt
    file_path: /share/sensor/MuellabfuhrZaehler.json
    value_template: '{{ value_json.abgeholt }}'
  - platform: file
    name: MuellabfuhrSparziel
    file_path: /share/sensor/MuellabfuhrZaehler.json
    value_template: '{{ value_json.sparziel }}'
  - platform: version
    source: hassio
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

vicare:
  username: !secret vicare_user
  password: !secret vicare_pass

binary_sensor:
  - platform: template
    sensors:
      allefenster:
        friendly_name: "Alle Fenster"
        entity_id: group.fenster
        value_template: "{{ expand('group.fenster') | selectattr('state', 'eq', 'on') | list | count > 0 }}"
      zirkulationspumpe:
        friendly_name: "Zirkulationspumpe"
        value_template: "{{ state_attr('climate.vicare_heating', 'circulationpump_active') }}"
      waschmaschine:
        friendly_name: "Waschmaschine läuft"
        value_template: "{{ states('sensor.waschmaschine_leistung_average')|float > 4.0 }}"
        delay_off:
          minutes: 3
        delay_on:
          minutes: 6
      homeoffice:
        friendly_name: "Home Office"
        value_template: "{{ is_state('input_boolean.homeoffice', 'on') }}"
      jemandzuhause:
        friendly_name: "Jemand ist zu Hause"
        value_template: >-
                        {{is_state('sensor.thomas_status','zu Hause') or 
                        is_state('sensor.thomas_status','gerade angekommen') or
                        is_state('sensor.steffi_status','zu Hause') or 
                        is_state('sensor.steffi_status','gerade angekommen')}}

input_boolean:
  wochenende:
    name: Wochenende
  homeoffice:
    name: Home Office

input_number:
  muellabfuhr_slider:
    name: Müllabfuhr abgeholt
    min: 0
    max: 27
    step: 1
  temperatur_niedrig:
    name: niedrige Temperatur
    min: 15
    max: 25
    step: 1
    initial: 18
  temperatur_hoch:
    name: hohe Temperatur
    min: 15
    max: 25
    step: 1
    initial: 21

input_select:
  thomas_status_dropdown:
    name: Thomas
    options:
      - zu Hause
      - gerade angekommen
      - gerade raus
      - unterwegs
      - lange weg
  steffi_status_dropdown:
    name: Steffi
    options:
      - zu Hause
      - gerade angekommen
      - gerade raus
      - unterwegs
      - lange weg

switch:
  - platform: mqtt
    name: "Sonoff Rechner"
    state_topic: "home/thomaszimmer/sonoff/stat/RESULT" #"stat/sonoff/POWER"
    value_template: '{{ value_json["POWER"] }}'
    command_topic: "home/thomaszimmer/sonoff/cmnd/POWER" #"cmnd/sonoff/POWER"
    availability_topic: "home/thomaszimmer/sonoff/tele/LWT" #"tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: wake_on_lan
    mac: "00-11-32-37-21-3D"
    name: "Synology NAS"
    host: "192.168.2.151"
    turn_off:
      service: shell_command.turn_off_nas
      data:
        secret_url: !secret syno_cmd_url
  - platform: wake_on_lan
    mac: "BC-5F-F4-59-14-77"
    name: "Steffi Desktop"
    host: "192.168.2.99"
    turn_off:
      service: shell_command.hibernate_steffidesktop
      data:
        password: !secret http_password
  - platform: mqtt
    name: "Sonoff Waschmaschine"
    state_topic: "home/keller/waschmaschine/stat/RESULT" #"stat/sonoff/POWER"
    value_template: '{{ value_json["POWER"] }}'
    command_topic: "home/keller/waschmaschine/cmnd/POWER" #"cmnd/sonoff/POWER"
    availability_topic: "home/keller/waschmaschine/tele/LWT" #"tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Deko2"
    state_topic: "home/deko/deko2/stat/RESULT" #"stat/sonoff/POWER"
    value_template: '{{ value_json["POWER"] }}'
    command_topic: "home/deko/deko2/cmnd/POWER" #"cmnd/sonoff/POWER"
    availability_topic: "home/deko/deko2/tele/LWT" #"tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Deko4"
    state_topic: "home/deko/deko4/stat/RESULT" #"stat/sonoff/POWER"
    value_template: '{{ value_json["POWER"] }}'
    command_topic: "home/deko/deko4/cmnd/POWER" #"cmnd/sonoff/POWER"
    availability_topic: "home/deko/deko4/tele/LWT" #"tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Deko1"
    state_topic: "home/deko/deko1/stat/RESULT" #"stat/sonoff/POWER"
    value_template: '{{ value_json["POWER"] }}'
    command_topic: "home/deko/deko1/cmnd/POWER" #"cmnd/sonoff/POWER"
    availability_topic: "home/deko/deko1/tele/LWT" #"tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Stern"
    state_topic: "home/deko/stern/stat/RESULT" #"stat/sonoff/POWER"
    value_template: '{{ value_json["POWER"] }}'
    command_topic: "home/deko/stern/cmnd/POWER" #"cmnd/sonoff/POWER"
    availability_topic: "home/deko/stern/tele/LWT" #"tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

light:
  - platform: mqtt
    schema: json
    name: "LixieClock"
    state_topic: "home/wohnzimmer/lixie"
    command_topic: "home/wohnzimmer/lixie/cmd"
    brightness: true
    rgb: true
    optimistic: false
    qos: 0
    retain: true

cover:
  - platform: mqtt
    name: "Rollladen Thomas"
    command_topic: "shellies/shellyswitch25-E62E12/roller/0/command"
    position_topic: "shellies/shellyswitch25-E62E12/roller/0/pos"
    set_position_topic: "shellies/shellyswitch25-E62E12/roller/0/command/pos"
    availability_topic: "shellies/shellyswitch25-E62E12/online"
    payload_available: "true"
    payload_not_available: "false"
    qos: 0
    retain: false
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    position_open: 100
    position_closed: 0
    # value_template: '{{ value.x }}'
    device_class: shutter

shell_command:
  turn_off_nas: 'curl {{ secret_url }}'
  shutdown_steffidesktop: 'curl -u User:{{password}} -k http://192.168.2.99:8000/?action=System.Shutdown'
  restart_steffidesktop: 'curl -u User:{{password}} -k http://192.168.2.99:8000/?action=System.Restart'
  hibernate_steffidesktop: 'curl -u User:{{password}} -k http://192.168.2.99:8000/?action=System.Hibernate'

eufy:
  username: !secret eufy_user
  password: !secret eufy_pass

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Media Players
media_player:
  - platform: androidtv
    host: 192.168.2.50
    name: Fernseher
    adb_server_ip: 127.0.0.1

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.de

# # Cloud
cloud:

# Google
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

# mqtt
mqtt:
  discovery: true
  broker: core-mosquitto
  username: !secret mqtt_user
  password: !secret mqtt_pass

duckdns:
  domain: helmkeaufdemkamp
  access_token: !secret ducktoken

device_tracker:
  - platform: nmap_tracker
    hosts: 
      # - 192.168.2.0/24
      - 192.168.2.98
      - 192.168.2.97
    home_interval: 10

person:

notify:
  - name: MuellabfuhrZaehler
    platform: file
    filename: /share/sensor/MuellabfuhrZaehler.json

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
