homeassistant:
  customize: !include customize.yaml

  whitelist_external_dirs:
    - /config/sensor
    - /share/sensor
  
  packages: !include_dir_named integrations

# # InfluxDB
#influxdb:
#  host: a0d7b954-influxdb
#  port: 8086
#  database: homeassistant
#  username: homeassistant
#  password: !secret http_password
#  max_retries: 3
#  default_measurement: state

#android_ip_webcam:
#  - host: 192.168.2.127
#    sensors:
#      - battery_level
#      - battery_temp
#      - light
#    switches:
#      - night_vision
#      - torch

