title: Jarvis

views:
  - title: Übersicht
    theme: midnight
    panel: true
    cards:
      - type: horizontal-stack
        cards:
        - type: vertical-stack
          cards:
          - type: glance
            title: Fenster
            show_state: false
            entities:
              - entity: binary_sensor.fenster_thomas
              - entity: binary_sensor.haustur
              - entity: binary_sensor.fenster_kueche
              - entity: binary_sensor.fenster_wohnzimmer
          - type: entity-filter
            entities:
              - entity: binary_sensor.fenster_thomas
              - entity: binary_sensor.haustur
              - entity: binary_sensor.fenster_kueche
              - entity: binary_sensor.fenster_wohnzimmer
            state_filter:
              - "on"
            card:
              type: glance
              show_state: false
              title: Offene Fenster
        - type: weather-forecast
          entity: weather.openweathermap
        - type: entities
          title: Waschmaschine
          entities:
            - entity: binary_sensor.waschmaschine
              name: Status
              secondary_info: last-changed