esphome:
  name: test
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "bal"
  password: "vlnslbn"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "OewtKoYuCU2x"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
